name: smallnotes
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0


  
  cupertino_icons: ^1.0.2

  # for generate key
  uuid: ^3.0.6  

  # log
  logger: ^1.1.0
  
  # color picker
  flutter_colorpicker: ^1.0.3

  # providers
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1

  # painting
  custom_clippers: ^2.0.0
  
  # local database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # assets
  flutter_svg: ^1.1.4
  image_gallery_saver: ^1.7.1

  # fonts
  google_fonts: ^3.0.1
  
  flutter_gen: ^4.3.0
  rate_my_app: ^1.1.3
  rating_dialog: ^2.0.4
  share_plus: ^4.0.4
  store_redirect: ^2.0.1

  # other
  async: ^2.8.2
  url_launcher: ^6.1.4

  # animations
  loading_indicator: ^3.1.0
  drag_select_grid_view: ^0.6.1

  # icons 
  phosphor_flutter: ^1.4.0
  day_night_switcher: ^0.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_gen_runner: ^4.3.0
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  hive_generator: ^1.1.3

flutter:

  uses-material-design: true

  assets:
    - assets/i18n/
    - assets/svg/
    - assets/img/
    - assets/google_fonts/RubikMoonrocks-Regular.ttf
  
